# Generated by Django 4.2.6 on 2023-12-28 11:45

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('constructions', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Project_members',
            new_name='ProjectMembers',
        ),
    ]
