# Generated by Django 4.2.6 on 2023-12-28 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('constructions', '0002_rename_project_members_projectmembers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectmembers',
            old_name='project',
            new_name='project_id',
        ),
        migrations.RenameField(
            model_name='projectmembers',
            old_name='member',
            new_name='user_phone',
        ),
    ]
