# Generated by Django 4.2.6 on 2023-12-28 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('constructions', '0003_rename_project_projectmembers_project_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectmembers',
            old_name='user_phone',
            new_name='member',
        ),
        migrations.RenameField(
            model_name='projectmembers',
            old_name='project_id',
            new_name='project',
        ),
    ]
