# Generated by Django 4.2.6 on 2023-12-28 21:30

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('constructions', '0004_rename_user_phone_projectmembers_member_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProjectMembers',
            new_name='ProjectMember',
        ),
    ]
