# Generated by Django 4.2.6 on 2023-12-29 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('constructions', '0005_rename_projectmembers_projectmember'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectmember',
            old_name='member',
            new_name='phone_number',
        ),
    ]
