# Generated by Django 4.2.6 on 2024-02-01 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constructions', '0007_rename_phone_number_projectmember_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='outer_design',
            field=models.CharField(choices=[('Residential', 'Residential'), ('Commercial', 'Commercial'), ('industrial', 'industrial'), ('General', 'General'), ('Farms', 'Farms')], default='ٌResidential', max_length=255),
        ),
    ]
