# Generated by Django 4.2.6 on 2024-02-12 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constructions', '0009_project_creation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='outer_design',
            field=models.CharField(choices=[('Residential', 'Residential'), ('Commercial', 'Commercial'), ('Industrial', 'Industrial'), ('General', 'General'), ('Farms', 'Farms')], default='ٌResidential', max_length=255),
        ),
    ]
