# Generated by Django 4.2.6 on 2024-02-19 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constructions', '0010_alter_project_outer_design'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='location',
            field=models.CharField(max_length=255),
        ),
    ]
