# Generated by Django 4.2.6 on 2024-02-19 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constructions', '0011_alter_project_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='outer_design',
            field=models.CharField(max_length=255),
        ),
    ]
