# Generated by Django 4.2.6 on 2024-02-26 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constructions', '0012_alter_project_outer_design'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_number',
            field=models.CharField(max_length=255),
        ),
    ]
