# Generated by Django 4.2.6 on 2024-01-08 09:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import offer_price.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('constructions', '0007_rename_phone_number_projectmember_member'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfferPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField(auto_created=True, auto_now=True)),
                ('worker_name', models.CharField(max_length=255)),
                ('file', models.FileField(blank=True, null=True, upload_to='offer_price_files', validators=[offer_price.models.validate_file_size])),
                ('note', models.TextField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='constructions.project')),
            ],
        ),
        migrations.CreateModel(
            name='OfferPriceComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField(auto_created=True, auto_now=True)),
                ('comment', models.TextField()),
                ('file', models.FileField(blank=True, null=True, upload_to='offer_price_comment_files', validators=[offer_price.models.validate_file_size])),
                ('offer_price', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='offer_price.offerprice')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
