# Generated by Django 4.2.6 on 2024-01-10 11:30

import django.core.validators
from django.db import migrations, models
import offer_price.models


class Migration(migrations.Migration):

    dependencies = [
        ('offer_price', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offerprice',
            old_name='worker_name',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='offerpricecomment',
            old_name='offer_price',
            new_name='report',
        ),
        migrations.AddField(
            model_name='offerprice',
            name='bid_price',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='offerprice',
            name='project_duration',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='offerprice',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='report_files', validators=[offer_price.models.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='offerpricecomment',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='report_comment_files', validators=[offer_price.models.validate_file_size]),
        ),
    ]
