# Generated by Django 4.2.6 on 2024-01-07 12:28

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import report.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('constructions', '0007_rename_phone_number_projectmember_member'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField(auto_created=True, auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('project_duration', models.CharField(blank=True, max_length=255, null=True)),
                ('bid_price', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('file', models.FileField(blank=True, null=True, upload_to='approval_files', validators=[report.models.validate_file_size])),
                ('note', models.CharField(max_length=255)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='constructions.project')),
            ],
        ),
        migrations.CreateModel(
            name='ReportComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField(auto_created=True, auto_now=True)),
                ('comment', models.CharField(max_length=255)),
                ('file', models.FileField(blank=True, null=True, upload_to='approval_comment_files', validators=[report.models.validate_file_size])),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.report')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
