# Generated by Django 4.2.6 on 2024-01-08 09:15

from django.db import migrations, models
import report.models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='report_files', validators=[report.models.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='report',
            name='note',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='reportcomment',
            name='comment',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='reportcomment',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='report_comment_files', validators=[report.models.validate_file_size]),
        ),
    ]
