# Generated by Django 4.2.6 on 2024-01-10 11:30

from django.db import migrations, models
import report.models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0002_alter_report_file_alter_report_note_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='title',
            new_name='worker_name',
        ),
        migrations.RenameField(
            model_name='reportcomment',
            old_name='report',
            new_name='offer_price',
        ),
        migrations.RemoveField(
            model_name='report',
            name='bid_price',
        ),
        migrations.RemoveField(
            model_name='report',
            name='project_duration',
        ),
        migrations.AlterField(
            model_name='report',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='offer_price_files', validators=[report.models.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='reportcomment',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='offer_price_comment_files', validators=[report.models.validate_file_size]),
        ),
    ]
