# Generated by Django 4.2.6 on 2024-01-10 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0003_rename_title_report_worker_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reportcomment',
            old_name='offer_price',
            new_name='report',
        ),
    ]
