# Generated by Django 4.2.6 on 2024-02-01 13:57

from django.db import migrations, models
import report.models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0004_rename_offer_price_reportcomment_report'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='worker_name',
            new_name='title',
        ),
        migrations.AlterField(
            model_name='report',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='report_files', validators=[report.models.validate_file_size]),
        ),
    ]
