# Generated by Django 4.2.6 on 2024-02-02 10:38

from django.db import migrations, models
import report.models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0005_rename_worker_name_report_title_alter_report_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportcomment',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='report_comment_files', validators=[report.models.validate_file_size]),
        ),
    ]
