# Generated by Django 4.2.6 on 2024-01-01 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('additional_modification', '0002_additionalmodification_date_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionalmodification',
            name='date_created',
            field=models.DateField(auto_created=True, auto_now=True),
        ),
    ]
