# Generated by Django 4.2.6 on 2024-01-08 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approval', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approval',
            name='note',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='approvalcomment',
            name='comment',
            field=models.TextField(),
        ),
    ]
