# Generated by Django 4.2.6 on 2024-01-18 13:53

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import pricing_tender.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PricingTender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=255)),
                ('planing', models.FileField(blank=True, null=True, upload_to='PricingTender_files/planing', validators=[pricing_tender.models.validate_file_size])),
                ('three_d', models.FileField(blank=True, null=True, upload_to='PricingTender_files/three_d', validators=[pricing_tender.models.validate_file_size])),
                ('quantities_and_specifications', models.FileField(blank=True, null=True, upload_to='PricingTender_files/quantities_and_specifications', validators=[pricing_tender.models.validate_file_size])),
                ('other_files', models.FileField(blank=True, null=True, upload_to='PricingTender_files/other_files', validators=[pricing_tender.models.validate_file_size])),
            ],
        ),
        migrations.CreateModel(
            name='PricingTenderContractor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contractor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('pricing_tender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pricing_tender.pricingtender')),
            ],
        ),
        migrations.CreateModel(
            name='OfferPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField(auto_created=True, auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('project_duration', models.CharField(blank=True, max_length=255, null=True)),
                ('bid_price', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('file', models.FileField(blank=True, null=True, upload_to='report_files', validators=[pricing_tender.models.validate_file_size])),
                ('note', models.TextField()),
                ('PricingTender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pricing_tender.pricingtender')),
            ],
        ),
    ]
