# Generated by Django 4.2.6 on 2024-01-18 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing_tender', '0003_pricingtender_pricing_tender_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricingtender',
            name='date_created',
            field=models.DateField(auto_created=True, auto_now=True),
        ),
    ]
