# Generated by Django 4.2.6 on 2024-01-18 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pricing_tender', '0004_pricingtender_date_created'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offerprice',
            old_name='PricingTender',
            new_name='pricing_tender',
        ),
    ]
