# Generated by Django 4.2.6 on 2024-01-03 16:45

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import progress_step.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('constructions', '0007_rename_phone_number_projectmember_member'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgressStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('order', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('is_finished', models.BooleanField(default=False)),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_steps', to='progress_step.progressstep')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='constructions.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProgressStepComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField(auto_created=True, auto_now=True)),
                ('comment', models.CharField(max_length=255)),
                ('file', models.FileField(blank=True, null=True, upload_to='additional_modification_comment_files', validators=[progress_step.models.validate_file_size])),
                ('sub_step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='progress_step.progressstep')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
