# Generated by Django 4.2.6 on 2024-01-04 11:17

from django.db import migrations, models
import progress_step.models


class Migration(migrations.Migration):

    dependencies = [
        ('progress_step', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progressstepcomment',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='progress_sub_step_comment_files', validators=[progress_step.models.validate_file_size]),
        ),
    ]
