# Generated by Django 4.2.6 on 2023-12-17 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_verifiedphone_expires_at_verifiedphone_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='verifiedphone',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
