# Generated by Django 4.2.6 on 2023-12-19 20:42

from django.db import migrations, models
import members.models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_verifiedphone_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cv',
            field=models.FileField(blank=True, null=True, upload_to='', validators=[members.models.validate_file_size]),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_picture', validators=[members.models.validate_file_size]),
        ),
        migrations.AddField(
            model_name='user',
            name='services',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('1', '1'), ('item_key2', 'Item title 1.2'), ('item_key3', 'Item title 1.3'), ('item_key4', 'Item title 1.4'), ('item_key5', 'Item title 1.5')], default='None', max_length=20),
        ),
    ]
