# Generated by Django 4.2.6 on 2023-12-27 19:23

from django.db import migrations, models
import members.models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0007_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Commercial_license',
            field=models.FileField(blank=True, null=True, upload_to='', validators=[members.models.validate_file_size]),
        ),
        migrations.AddField(
            model_name='user',
            name='job_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
