# Generated by Django 4.2.6 on 2023-12-27 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0008_user_commercial_license_user_job_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='projects_limits',
            field=models.IntegerField(default=0),
        ),
    ]
