# Generated by Django 4.2.6 on 2024-01-18 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0017_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='role',
            field=models.CharField(blank=True, choices=[('Consultant', 'Consultant'), ('User', 'User'), ('Contractor', 'Contractor'), ('Owner', 'Owner')], max_length=255, null=True),
        ),
    ]
